version: "3.4"

volumes:
  test_firefox:
  test_tor:

services:
  neko:
    image: "ghcr.io/haiphamhoang/neko-xfce-firefox:master"
    # build: .
    # restart: "unless-stopped"
    shm_size: "2gb"
    volumes:
    - test_firefox:/home/neko/.mozilla/firefox/profile.default
    - test_tor:/home/neko/app/tor-browser/Browser/TorBrowser/Data/Browser/profile.default
    ports:
      - "18080:8080"
      - "28881:28881"
    environment:
      NEKO_SCREEN: '1360x768@60'
      NEKO_PASSWORD: userpw
      NEKO_PASSWORD_ADMIN: adminpw
      #NEKO_EPR: 52000-52100
      NEKO_TCPMUX: 28881
      NEKO_UDPMUX: 28881
      NEKO_ICELITE: 1


